### ISSUE TITLE
!claim command seems to be seriously bugged

### ISSUE THREAD

**Issue by sircodemane** [TheCrunchy/FixPlayerCommand#14] opened 2020-09-03 01:23 UTC
According to the docs listed here https://torchapi.net/plugins/item/b2a19d95-1bfa-4884-9a83-39b56f84ae0d:
```
!claim - Claim ownership of a grid if its shared and over the percentage required
```
The interpreted behavior is that this should only work if a player owns at least some unknown percentage of blocks on a grid. However, a player on our server was able to take ownership of any grid, friendly or enemy, and take claim of it using the `!claim` command. Did not hack any blocks, did not own any blocks, just fly up to any grid and take ownership of it. Player was also not an admin or have any special privileges.

**Comment by TheCrunchy** [comment] 2020-09-03 01:43
Disabled the command for now, will look into why its bugged

**Comment by TheCrunchy** [comment] 2020-09-03 02:18
Pushed a fix, should work as intended now

**Closed as completed by TheCrunchy** 2020-09-03 02:18 UTC
